# Generated by Django 4.0.4 on 2022-06-12 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_player', '0003_alter_song_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='desciption',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='play_time',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_player.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
